### ISSUE TITLE
Cannot override a mock in an inner context

### ISSUE THREAD

**Issue by robkinyon** [mdurban/rspec-bash#57]
If I override a mock in an inner context, it should override the mock in an outer context with the same arguments. I should continue being able to add additional `.with_args()` options to a mock within an inner context without affecting the other `.with_args()` options.
```ruby
describe 'outermost' do
    let(:env) { create_stubbed_env }
    let!(:mymock) { env.stub_command('mycommand') }

    before {
        mymock.with_args('foo').outputs('Hello').returns_exitstatus(0)
    }

    context 'mycommand fails' do
        before {
            mymock.with_args('foo').outputs("").returns_exitstatus(1)
        }

        # Do some test 
    end

    # Do a huge number of other tests where mycommand succeeds
end
```

**Comment by bennyhat** [comment]
This should be addressed by https://github.com/mdurban/rspec-bash/pull/84 - or rather the behavior would now be:

Outer with_args sets mymock to return 'Hello' and 0. Inner with_args sets mymock to return '' and 1 instead. Due to a goofy use case, before #84 the outputs would stack and would make it not work this way.
